In [27]:
# Variabels and Data Types
# Variabels Assignment

x = 5
x

5

In [3]:
# Calculations With Variables

print(x + 2)
print(x - 2)
print(x * 2)
print(x ** 2)
print(x % 2)
print(x / float(2))

7
3
10
25
1
2.5


In [4]:
# Types and Type Conversion

print('5', '3.45', 'True')
print(5, 3, 1)
print(5.0, 1.0)
print(True, True, False)

5 3.45 True
5 3 1
5.0 1.0
True True False


In [5]:
# Asking For Help

help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

In [6]:
# String

my_string = 'dlfmldmmdl;f'
print(my_string)

dlfmldmmdl;f


In [7]:
# String Operstions

print(my_string * 2)
print(my_string + 'Innit')
print('m' in my_string)
print(my_string[3])
print(my_string[4:9])

dlfmldmmdl;fdlfmldmmdl;f
dlfmldmmdl;fInnit
True
m
ldmmd


In [8]:
# String Methods

print(my_string.upper())
print(my_string.lower())
print(my_string.count('m'))
print(my_string.replace('d', 'm'))
print(my_string.strip())

DLFMLDMMDL;F
dlfmldmmdl;f
3
mlfmlmmmml;f
dlfmldmmdl;f


In [9]:
# List

a = 'is'
b = 'nice'
my_list = ['my', 'list', a, b]
my_list2 = [[4, 5, 6, 7, 9], [3, 4, 5, 6, 1]]
print(my_list)
print(my_list2)

['my', 'list', 'is', 'nice']
[[4, 5, 6, 7, 9], [3, 4, 5, 6, 1]]


In [10]:
# Selecting List Elements

# Subset

print(my_list[1])
print(my_list[-3])

list
list


In [11]:
#Slice

print(my_list[1:3])
print(my_list[1:])
print(my_list[:3])
print(my_list[:])

['list', 'is']
['list', 'is', 'nice']
['my', 'list', 'is']
['my', 'list', 'is', 'nice']


In [12]:
# Subset Lists of Lists

print(my_list2[1][0])
print(my_list2[1][:2])

3
[3, 4]


In [13]:
# List Operations

print(my_list + my_list)
print(my_list * 2)
print(len(my_list2) > 2)

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']
['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']
False


In [40]:
# List Operation

my_list = ['my', 'list', a, b]
print(my_list.extend('!'))
print(my_list.pop(-1))


None
!


In [41]:
# Libraries
# Import numpy

import numpy as np

# Selective import
# Numpy Arrys

my_list = [1, 2, 3, 4]

my_array = np.array(my_list)
print(my_array)

my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
print(my_2darray)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [42]:
# Selecting Numpy Array Elements
# Subset

print(my_array[1])

2


In [43]:
# Slice

my_array[0:2]

# Subset 2D Numpy arrays

print(my_2darray[:, 0])


[1 4]


In [44]:
# Numpy Array Operations

print(my_array > 3)
print(my_array * 2)
print(my_array + np.array([5, 6, 7, 8]))

[False False False  True]
[2 4 6 8]
[ 6  8 10 12]


In [45]:
# Numpy Array Functions

print(my_array.shape)
print(np.append(my_array, 5))
print(np.insert(my_array, 1, 5))
print(np.delete(my_array, [1]))
print(np.mean(my_array))
print(np.median(my_array))
print(np.corrcoef(my_array))
print(np.std(my_array))
print("")

(4,)
[1 2 3 4 5]
[1 5 2 3 4]
[1 3 4]
2.5
2.5
1.0
1.118033988749895



In [46]:
# Python For Data Science
# Importing Data in Python

import pandas as pd

# Help

print(np.info(np.ndarray.dtype))
print(help(pd.read_csv))

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
None
Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer: Union[str, pathlib.Path, IO[~AnyStr]], sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal: str = '.', lineterminator=None, quotechar='"',