In [3]:
# Creating Arrays
from numpy.doc import misc
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
c = np.array([[(1.5, 2, 3,), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)
print(a)
print(b)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [4]:
# Initial Placeholders

print(np.zeros((3, 4)))
print(np.ones((2, 3, 4), dtype=np.int16))
d = np.arange(10, 25, 5)
print(d)
print(np.linspace(0, 2, 9))

print(np.full((2, 2), 7))
print(np.eye(2))
print(np.random.random((2, 2)))
print(np.empty((3, 2)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.84304375 0.65261974]
 [0.36452178 0.75548561]]
[[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


In [5]:
# I/O

np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

array([1, 2, 3])

In [6]:
# Insperting Your Array

print(a.shape)
print(len(a))
print(b.ndim)
print(c.size)
print(b.dtype)
print(b.dtype.name)
print(b.astype(int))

(3,)
3
2
12
float64
float64
[[1 2 3]
 [4 5 6]]


In [7]:
# Asking For Help

print(np.info(np.ndarray.dtype))

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
None


In [8]:
# Array Mathematics

print(a - b)
print(np.subtract(a, b))

print(a + b)
print(np.add(a, b))

print(a / b)
print(np.divide(a, b))

print(a * b)
print(np.multiply(a, b))

print(np.exp(b))
print(np.sqrt(b))
print(np.sin(b))
print(np.cos(b))
print(np.log(b))

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
[[2.5 4.  6. ]
 [5.  7.  9. ]]
[[2.5 4.  6. ]
 [5.  7.  9. ]]
[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]
[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]
[[  4.48168907   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.99749499  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.0707372  -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[0.40546511 0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [9]:
# Comparison
print(a == b)
print(a < 2)
print(np.array_equal(a, b))

[[False  True  True]
 [False False False]]
[ True False False]
False


In [10]:
# Copying Arrays
h = a.view()
print(h)
print(np.copy(a))
h = a.copy()
print(h)

[1 2 3]
[1 2 3]
[1 2 3]


In [11]:
# Subsetting, Slicing, Indexing
# Subsetting
print(a[2])
print(b[1, 2])

3
6.0


In [12]:
# Slicing
print(a[0:2])
print(b[0:2, 1])
print(b[:1])
print(c[1, ...])
print(a[::-1])

[1 2]
[2. 5.]
[[1.5 2.  3. ]]
[[3. 2. 1.]
 [4. 5. 6.]]
[3 2 1]


In [13]:
# Boolean Indexing
print(a[a < 2])

[1]


In [14]:
# Fancy Indexing
print(b[[1, 0, 1, 0], [0, 1, 2, 0]])
print(b[[1, 0, 1, 0]][:, [0, 1, 2, 0]])

[4.  2.  6.  1.5]
[[4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]
 [4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]]


In [15]:
# Array Manipulation
# Transposing Array
i = np.transpose(b)
print(i)
print(i.T)

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [16]:
# Changing Array Shape
print(b.ravel())
print(c.reshape(3, -2))

[1.5 2.  3.  4.  5.  6. ]
[[1.5 2.  3.  4. ]
 [5.  6.  3.  2. ]
 [1.  4.  5.  6. ]]


In [17]:
# Adding/Removing Elements
print(h.resize((1, 2)))
print(np.append(a, d))
print(np.insert(a, 1, 5))
print(np.delete(a, [1]))

None
[ 1  2  3 10 15 20]
[1 5 2 3]
[1 3]


In [20]:
# Python For Data Science
# SciPy
# Interacting With NumPy
a = np.array([1, 2, 3])
b = np.array([(1 + 5j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]])

In [19]:
# Index Tricks
print(np.mgrid[0:5, 0:5])
print(np.ogrid[0:2, 0:2])
print(np.r_[3, [0] * 5, -1:1:10j])

[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
[array([[0],
       [1]]), array([[0, 1]])]
[ 3.          0.          0.          0.          0.          0.
 -1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [21]:
# Shape Manipulation
print(np.transpose(b))
print(b.flatten())

[[1.+5.j 0.+4.j]
 [0.+2.j 0.+5.j]
 [0.+3.j 0.+6.j]]
[1.+5.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j]


In [22]:
# Vectoring Functions
def myfunc(a):
    if a < 0:
        return a * 2
    else:
        return a / 2
np.vectorize(myfunc)

In [23]:
# Type Handiling
print(np.real(b))
print(np.imag(b))
print(np.real_if_close(c, tol=1000))
print(np.cast['f'](np.pi))

[[1. 0. 0.]
 [0. 0. 0.]]
[[5. 2. 3.]
 [4. 5. 6.]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
3.1415927


In [24]:
# Other Usefuk Functions
print(np.angle(b, deg=True))
g = np.linspace(0, np.pi, num=5)
print(g)
g[3:] += np.pi
print(np.unwrap(g))
print(np.logspace(0, 10, 3))
np.select([c < 4], [c * 2])

[[78.69006753 90.         90.        ]
 [90.         90.         90.        ]]
[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[ 0.          0.78539816  1.57079633 -0.78539816  0.        ]
[1.e+00 1.e+05 1.e+10]


array([[[3., 4., 6.],
        [0., 0., 0.]],

       [[6., 4., 2.],
        [0., 0., 0.]]])

In [25]:
#Linear Algebra
#Creating Matrices
from scipy import linalg, sparse
A=np.array(np.random.random((2, 2)))
print(A)
B=np.asmatrix(b)
print(B)
C=np.mat(np.random.random((10, 5)))
print(C)
D=np.mat([[3, 4], [5, 6]])
print(D)

[[0.01182878 0.57259173]
 [0.13562455 0.56060068]]
[[1.+5.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.01988945 0.95767483 0.27173609 0.20417737 0.2654313 ]
 [0.79692592 0.42796356 0.27376735 0.29962726 0.83024311]
 [0.71095359 0.51043842 0.44903147 0.81218903 0.03002282]
 [0.79051209 0.5249782  0.4586493  0.26439124 0.10948093]
 [0.19459514 0.74976417 0.0199631  0.65538642 0.73004258]
 [0.06915383 0.5403212  0.75872065 0.68954846 0.81690465]
 [0.57694187 0.46661959 0.64548787 0.42689731 0.85482404]
 [0.49779118 0.8106743  0.06770207 0.99370093 0.41557373]
 [0.02420213 0.40412845 0.11032269 0.46882147 0.61676228]
 [0.94867452 0.82116009 0.5477509  0.39058744 0.93515509]]
[[3 4]
 [5 6]]


In [26]:
#Basic Matrix Routines
#Creating Sparse Matrices
F=np.eye(3, k=1)
print(F)
G=np.mat(np.identity(2))
print(G)
C[C>0.5]=0
H=sparse.csr_matrix(C)
I=sparse.csr_matrix(D)
J=sparse.dok_matrix(A)
print(sparse.isspmatrix_csc(A))
print(H, I, J)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0.]
 [0. 1.]]
False
  (0, 0)	0.01988945023959121
  (0, 2)	0.271736085551067
  (0, 3)	0.2041773698616549
  (0, 4)	0.2654313022913771
  (1, 1)	0.4279635568937554
  (1, 2)	0.273767352210075
  (1, 3)	0.29962726035565634
  (2, 2)	0.449031474852726
  (2, 4)	0.030022815810719528
  (3, 2)	0.4586492956731376
  (3, 3)	0.2643912402574894
  (3, 4)	0.1094809286908135
  (4, 0)	0.19459513684173602
  (4, 2)	0.019963101136562966
  (5, 0)	0.06915382887916344
  (6, 1)	0.46661959372163253
  (6, 3)	0.4268973084586074
  (7, 0)	0.49779117963532526
  (7, 2)	0.06770207350966984
  (7, 4)	0.41557372862178876
  (8, 0)	0.024202129851114806
  (8, 1)	0.4041284450401136
  (8, 2)	0.11032269320855304
  (8, 3)	0.46882146938184066
  (9, 3)	0.39058744390490374   (0, 0)	3
  (0, 1)	4
  (1, 0)	5
  (1, 1)	6   (0, 0)	0.0118287834411267
  (0, 1)	0.5725917336297467
  (1, 0)	0.1356245529710961
  (1, 1)	0.5606006793042437


In [27]:
#Inverse
print(linalg.inv(A))
#Transposition
print(A.T)
#Trace
print(np.trace(A))
#Norm
print(linalg.norm(A))
print(linalg.norm(A, 1))
print(linalg.norm(A, np.inf))
#Rank
print(np.linalg.matrix_rank(C))
#Determinant
print(linalg.det(A))
#Solving linear problems
print(linalg.solve(A, b))
E=np.mat(a).T
print(E)
print(linalg.lstsq(F, E))
#Generalized inverse
print(linalg.pinv(C))
print(linalg.pinv2(C))

[[-7.89286343  8.06168904]
 [ 1.90949835 -0.16654095]]
[[0.01182878 0.13562455]
 [0.57259173 0.56060068]]
0.5724294627453704
0.8128150801651044
1.1331924129339903
0.6962252322753398
5
-0.07102627387604091
[[-7.89286343 -7.21756097j  0.        +24.52271835j
   0.        +24.69154396j]
 [ 1.90949835 +8.88132795j  0.         +2.98629193j
   0.         +4.72924933j]]
[[1]
 [2]
 [3]]
(array([[0.],
       [1.],
       [2.]]), array([], dtype=float64), 2, array([1., 1., 0.]))
[[-1.83022850e+00  3.65828040e-02  5.47066727e-01  1.80444582e-01
   2.23473980e+00  7.80195151e-01 -3.55826587e-01  1.08192645e+00
   3.72108304e-01  7.48798058e-01]
 [-8.30775665e-04  1.13438249e+00  3.23383372e-02 -7.81050747e-01
  -4.92969441e-01 -1.74023587e-01  8.71793126e-01  2.03958482e-01
   2.66573371e-01 -1.61387875e+00]
 [-1.84247625e-01  5.07860371e-01  1.23753620e+00  7.96825494e-01
   4.42608638e-01  1.36182842e-01 -4.13479161e-01 -1.81643892e-01
  -6.03972651e-02 -3.08239866e-01]
 [ 9.31940191e-02 -5.6987

In [28]:
#Matrix Functions
#Addition
print(np.add(A, D))
#Subtraction
print(np.subtract(A, D))
#Division
print(np.divide(A, D))
#Multiplication
print(A @ D)
print(np.multiply(D, A))
print(np.dot(A, D))
print(np.inner(A, D))
print(np.outer(A, D))
print(np.tensordot(A, D))
print(np.kron(A, D))
#Exponential Functions
print(linalg.expm(A))
#Trigonometric Functions
print(linalg.sinm(D))
#Hyperbolic Trigonometric Functions
print(linalg.sinhm(D))
#Matrix Square Root
print(linalg.sqrtm(A))
#Arbitrary Funcrions
print(linalg.funm(A, lambda x: x*x))

[[3.01182878 4.57259173]
 [5.13562455 6.56060068]]
[[-2.98817122 -3.42740827]
 [-4.86437545 -5.43939932]]
[[0.00394293 0.14314793]
 [0.02712491 0.09343345]]
[[2.89844502 3.48286554]
 [3.20987706 3.90610229]]
[[0.03548635 2.29036693]
 [0.67812276 3.36360408]]
[[2.89844502 3.48286554]
 [3.20987706 3.90610229]]
[[2.32585328 3.49469432]
 [2.64927638 4.04172684]]
[[0.03548635 0.04731513 0.05914392 0.0709727 ]
 [1.7177752  2.29036693 2.86295867 3.4355504 ]
 [0.40687366 0.54249821 0.67812276 0.81374732]
 [1.68180204 2.24240272 2.8030034  3.36360408]]
6.36758012552331
[[0.03548635 0.04731513 1.7177752  2.29036693]
 [0.05914392 0.0709727  2.86295867 3.4355504 ]
 [0.40687366 0.54249821 1.68180204 2.24240272]
 [0.67812276 0.81374732 2.8030034  3.36360408]]
[[1.05980146 0.78191797]
 [0.18520574 1.80919161]]
[[-0.07153039  0.17875259]
 [ 0.22344073  0.06253405]]
[[1716.2338286  2134.23383225]
 [2667.79229031 3316.90920278]]
[[0.12278573+0.27551759j 0.6024718 -0.2370649j ]
 [0.14270197-0.05615139j 0

In [30]:
#Decompositios
#Eiganvalues and Eigenvectors
la, v=linalg.eig(A)
l1, l2=la
print(la)
print(v[:,0])
print(v[:,1])
print(linalg.eigvals(A))
#Signular Value Decomposition
U, s, Vh=linalg.svd(B)
print(U, s, Vh)
M, N=B.shape
print(M, N)
#
#LU Decomposition
print('')
P, L, U=linalg.lu(C)
print(P, L, U)
print('')
#Sparse Matrix Decompositions
la, v=sparse.linalg.eigs(F, 1)
print(la, v)
print(sparse.linalg.svds(H, 2))

[-0.10486729+0.j  0.67729675+0.j]
[-0.97985746  0.19969816]
[-0.65222867 -0.75802227]
[-0.10486729+0.j  0.67729675+0.j]
[[-0.56260618-5.19885276e-19j  0.82672503-1.44338931e-17j]
 [-0.82386933-6.86557772e-02j -0.56066281-4.67219005e-02j]] [10.47751754  2.49431877] [[-0.07990722-5.83011023e-01j -0.03276338-5.00553588e-01j
  -0.03931606-6.32882215e-01j]
 [ 0.25651791+7.58112384e-01j -0.09365663-4.60993186e-01j
  -0.11238796-3.54325894e-01j]
 [-0.11479126-3.56425932e-04j -0.68803469-2.31721068e-01j
   0.64988974+1.93338508e-01j]]
2 3

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]] [[ 1.          0.          0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.        ]
 [ 0.